### ISSUE TITLE
Recommended addition to this setup

### ISSUE THREAD

**Issue by NerdyGriffin** [digitalcoyote/chocolatey-packages#21]
https://github.com/digitalcoyote/chocolatey-packages/blob/149528b716e4cbe88ecf3c420163ef3031650ac2/oh-my-posh/tools/chocolateyinstall.ps1#L20

I believe, in addition to the existing checks, it should also check `-or $line -like 'Set-PoshPrompt*'` which is an alternative way to set the theme instead of using `Invoke-Expression (oh-my-posh --init ...`, I believe that would be one possible fix to the issue discussed [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/673#issuecomment-824240372)

**Comment by digitalcoyote** [comment]
Oh-my-posh update script needs to be checked(seems to be behind currently). And this needs to be handled at the same time as that.
