### ISSUE TITLE
multipass not working with chocolateygui

### ISSUE THREAD

**Issue by jon-hedgerows** [digitalcoyote/chocolatey-packages#3]
multipass 1.2.1, installed on windows 10 pro 64 bit using chocolateygui.  Appears to install ok, but then "multipass" on the command line tries to run multipass from Program Files (x86), which fails, as it's installed in Program Files (withotu the (x86).  Uninstall fails in the same way.  Not sure whether this is a chocolateygui problem or a multipass packaging problem.

**Comment by digitalcoyote** [comment]
Can you try this again. I have a possible work-around, but I was able to install it with the Chocolatey GUI (Win 10 Pro 64-bit latest update). If not, if you are willing to test the install with a local package, I can send you one with the workaround.

**Comment by digitalcoyote** [comment]
I believe this has been corrected now, Feel free to open this back up if it still appears to be an issue.
