### ISSUE TITLE
oh-my-posh version inadvertently rolled back with install fix

### ISSUE THREAD

**Issue by jhitzke** [digitalcoyote/chocolatey-packages#32]
The latest commit to the repository fixed the install of `oh-my-posh`, but also inadvertently  rolled the version back as seen on the commit: [oh-my-posh/tools/chocolateyinstall.ps1](https://github.com/digitalcoyote/chocolatey-packages/commit/692f4d859e6cccb29dfba76c325af260c78f35ae#diff-218677625b20e01ac8ad2def4772098f087b1007cf92e87fd34be03269d73b2aL16)

I attempted to make the fix myself and commit a branch for a PR, but I don't believe I have repository rights, should be a simple fix though.

Thanks.

**Comment by digitalcoyote** [comment]
Again, thanks for the help. This will be fixed automatically next time oh-my-posh CI runs. I'm about to push up the corrected Tag for v7.49.0. It was failing validation on Chocolatey and had to be rebuilt using that commit (with the rest of the versions downgraded as well) to trigger the update.ps1 script.
