### ISSUE TITLE
oh-my-posh: wrong path to themes when install is done for all users

### ISSUE THREAD

**Issue by soredake** [digitalcoyote/chocolatey-packages#38]
When you install oh-my-posh for all users, the path for themes will be `C:\Program Files (x86)\oh-my-posh\themes\`  not `"$env:LocalAppDataPrograms/oh-my-posh/themes/`

Please, adjust the info that is printed after installation.

**Comment by digitalcoyote** [comment]
Should be fixed in the next update of Oh-My-Posh.

**Comment by soredake** [comment]
@digitalcoyote thanks! I've created pr to further fix path https://github.com/digitalcoyote/chocolatey-packages/pull/39
