### ISSUE TITLE
syncplay: update to 1.7.0-Beta1

### ISSUE THREAD

**Issue by soredake** [digitalcoyote/chocolatey-packages#40]
New version of syncplay is released https://github.com/Syncplay/syncplay/releases/tag/1.7.0-Beta1

**Comment by digitalcoyote** [comment]
I updated the script to allow pre-release versions (and fix various issues that were preventing it from updating properly). I intend to manually push the beta and the current stable version soon. I've got to help a relative with a cyber security incident this weekend. So I'll likely be unable to finish until Monday morning before work. 

If you need that specific version or the latest stable version more urgently, let me know an I will try to work it in around everything else.

**Comment by digitalcoyote** [comment]
[v1.6.9](https://community.chocolatey.org/packages/syncplay/1.6.9) is in review, it may take a bit for it to be moderated since this package isn't marked as trusted yet on Chocolatey.

**Comment by soredake** [comment]
`1.7.0-persistentrooms1` is really old and don't supports tls, can you publish `1.7.0-Beta1`?

**Comment by digitalcoyote** [comment]
I have it ready, but I'm letting 401 forbidden when I try to push it. I'll try to push it again today.

**Comment by digitalcoyote** [comment]
It looks like I have to wait on the stable version to be reviewed since that will make it actively listed on Chocolatey. I'm checking in every now and then. Typically it takes ~2 weeks for a review. If I had thought about this, I could have pushed the beta version first (pre-release builds are allowed to bypass moderator review). I'll try to update this ticket and push the beta as soon as the review is done.

**Comment by digitalcoyote** [comment]
Stable version is approved. I will hopefully remember  to push the beta after work.

**Comment by digitalcoyote** [comment]
It's live https://community.chocolatey.org/packages/syncplay/1.7.0-Beta1

due to the fact that I accidentally pushed an invalid version, and the older pre-release sorting higher, you'l need to explicitly update to or install by specifying the version
