### ISSUE TITLE
Add Bazelisk dependency on vcredist140

### ISSUE THREAD

**Issue by dibakch** [digitalcoyote/chocolatey-packages#43]
Bazel versions newer than 5.3.0 require an upgrade for `vcredist140`.  I'm not familiar with choco, but is it possible to add this as an explicit requirement for the Bazelisk package?

**Comment by digitalcoyote** [comment]
Shouldn't be too bad as I believe there is already a package for the dependency, it'll likely be tonight/tomorrow before I can get to it though

**Comment by digitalcoyote** [comment]
I haven't been able to get to this yet. If anyone wants to take a shot at it, I believe we just need to add a dependency on the vcredist140 package in chocolatey. That should automatically keep it up to date as long as they haven't explicitly pinned that package to a lower version.

**Comment by digitalcoyote** [comment]
@dibakch do you know what version is required? I can add a minimum version or even a specific version that it will depend on. Otherwise having any version installed through chocolatey will satisfy it, although it will default to the latest at time of install.

**Comment by dibakch** [comment]
We are using a specific version internally to have more build stability. I
think this would also make sense for the package. However, I do not know
about best practices for Choco or how this affects other packages that also
depend on this.

**Comment by digitalcoyote** [comment]
Sorry this got lost in the midst of  TODO pile. I've been doing a health checkup on the packages and I pushed this dependency up in a Fix Version for the latest Bazelisk.
