### ISSUE TITLE
syncplay: update to 1.7.0

### ISSUE THREAD

**Issue by soredake** [digitalcoyote/chocolatey-packages#44]
https://github.com/Syncplay/syncplay/releases/tag/v1.7.0

**Comment by digitalcoyote** [comment]
I was going to try to add this in last night, but Windows won't boot and I also for some reason had trouble starting my VM. And now we are sheltering due to the weather situation. I'll try to look into this soon, but at this rate it may take a couple more days.

**Comment by soredake** [comment]
@digitalcoyote i'm on windows, i can try updating it myself, i don't think the installer changed so it should be pretty easy.

**Comment by digitalcoyote** [comment]
If you want to take a look. Running the ./update script is supposed to build the update. If it does, the CI automatically publishes it to Chocolatey. I should be able to review any this afternoon, or I can take a look then (got the VM working last night after the storms passed).

**Comment by soredake** [comment]
```
❯ .\update.ps1
syncplay - checking updates using au version 2022.10.24

Exception: C:\Users\user\Documents\PowerShell\Modules\au\2022.10.24\Public\Update-Package.ps1:210
Line |
 210 |  … ion $Latest.Version)) { throw "Invalid version: $($Latest.Version)" }
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Invalid version:
```
Don't know why.

**Comment by digitalcoyote** [comment]
I couldn't figure it out, so I started basing the version off a different link. Powershell wasn't retrieving that one when I was grabbing the page source for some reason

**Comment by soredake** [comment]
https://github.com/Syncplay/syncplay/issues/599
