### ISSUE TITLE
Error when in stall on win 10 22h2 

### ISSUE THREAD

**Issue by iamsammajor** [digitalcoyote/chocolatey-packages#46]
im on 19045 ver, but when i ran choco install multipass still have error "ERROR: Hyper-V requires Windows 10 Pro/Enterprise with a build version > 17134"

**Comment by iamsammajor** [comment]
found the problem, im not using a eng language ver of windows, the caption value 'pro' is non-english, hence falied the installation.

**Comment by digitalcoyote** [comment]
The relevant output comes from this PowerShell command:
>  Get-cimInstance -ClassName Win32_OperatingSystem | Select-Object Caption, Version, BuildNumber

**Comment by iamsammajor** [comment]
pro would be '专业‘ enterprise would be '企业’

**Comment by digitalcoyote** [comment]
I just made the commit, but I'm going to have to spin up my windows VM, update it and then manually package the update since the automated environment doesn't support Hyper-V. Hopefully it will be updated and ready for tonight (my personal lapttop runs Linux). Sorry about the delay.

**Comment by digitalcoyote** [comment]
Just pushed this up as a Chocolatey Fix version (actual version appended with the date of the fix in format YYYYMMDD) should be ready to test out when it passes review
