### ISSUE TITLE
FileConverter v2

### ISSUE THREAD

**Issue by asheroto** [digitalcoyote/chocolatey-packages#48]
Hey there!

Happy to report that there is a new version of FileConverter, version 2.0, released yesterday.

It looks like the [update.ps1](https://github.com/digitalcoyote/chocolatey-packages/blob/master/file-converter/update.ps1) script should take care of it once triggered.

I also noticed that in your readme you are referencing [file-converter.org](https://file-converter.org), which appears to be the same software but it's actually NOT! I was almost tricked by this as well, even the webpages look identical. The correct URL is [file-converter.io](https://file-converter.io/)

https://github.com/digitalcoyote/chocolatey-packages/blob/master/README.md?plain=1#L24

You'll notice that on the `.org` site it wants you to download some "Zamzar" exe, vs the `.io` site it directs you to GitHub or refers you to the `.msi` file. 👀

Funny enough, even the `.nuspec` file contains this problem:
https://github.com/digitalcoyote/chocolatey-packages/blob/master/file-converter/file-converter.nuspec#L39

😊 Thanks for your time!

https://github.com/Tichau/FileConverter/releases

**Comment by digitalcoyote** [comment]
I'll try to get that corrected ASAP
