### ISSUE TITLE
[oh-my-posh] Installer has changed to MSI

### ISSUE THREAD

**Issue by flcdrg** [digitalcoyote/chocolatey-packages#53]
I gather Jan has changed the Windows installer to use MSI in the last few weeks

https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v24.9.0

The install-amd64.exe is not longer included in release assets.

**Comment by flcdrg** [comment]
For reference, here are the changes made for win-get support - https://github.com/JanDeDobbeleer/oh-my-posh/commit/45f448934c787de70ccbea8a6ccacba6ec0342e0

**Comment by flcdrg** [comment]
And looks like it's not a simple in-place upgrade. Guessing some of the package IDs have changed. Got this when I tried upgrading 
![image](https://github.com/user-attachments/assets/ac7826a7-f269-4127-a18a-f8ae9ec5e3df)

Might need to have a special step in the install script to uninstall the old version if it exists.

**Comment by flcdrg** [comment]
FYI working on a fix for this. Need to do some upgrade tests first before I submit a PR

**Comment by digitalcoyote** [comment]
Thanks for the PR, I haven't had any time to look into it.
