### ISSUE TITLE
informado

### ISSUE THREAD

**Issue by 030** [digitalcoyote/chocolatey-packages#6]
https://github.com/030/informado

**Comment by 030** [comment]
https://github.com/030/informado/issues/10

**Comment by 030** [comment]
@digitalcoyote windows binary has been created

**Comment by digitalcoyote** [comment]
I've suddenly realized how much I want a basic editor built into GitHub (like [Code spaces](https://github.com/features/codespaces/). It may be a day or two before I can get to a dev environment to work on this... 

That being said, if you want to ready a package like you did with n3rd, the only changes I had to make were:
- using raw.githack.com's CDN for the iconurl
- setting the version to 0.0.1 so the CD detects the current version on the first run.

**Comment by digitalcoyote** [comment]
https://chocolatey.org/packages/informado awaiting review

**Comment by 030** [comment]
https://rawcdn.githack.com/030/informado/218129ea0598dd2ad91a58a78e75ed7f77509bd6/logo/logo.png

**Comment by digitalcoyote** [comment]
Informado has been approved.
