### ISSUE TITLE
logo n3dr broken

### ISSUE THREAD

**Issue by 030** [digitalcoyote/chocolatey-packages#9]
I had to update the logo to make it snapcraft compatible. Therefor the following URL is applicable:

https://rawcdn.githack.com/030/n3dr/652333372e7dc758881becf42839c60d99ae7228/logo/logo.png

This will solve the broken logo issue in chocolatey.

**Comment by 030** [comment]
The current URL to the logo that is defined in chocolatey still renders the logo, but not in chocolatey. Do you know what is causing the issue?

**Comment by 030** [comment]
Related https://github.com/chocolatey/chocolatey.org/issues/652

**Comment by digitalcoyote** [comment]
Sorry about the delay, we were moving into our house (finally) and had a funeral delay us a bit. 

As of right now, I'm seeing the URL render on Chocolatey.org. Is this an issue in the ChocolateyGUI? or is it not rendering for you still?

**Comment by 030** [comment]
@digitalcoyote The logo is visible again. Thank you.
